[tools]
rust = "latest"

[env]
GH_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZFpYU29QYWRGb1RuQmM4aU0xV0hiQVBWZVF2YVhzTS9hck45alRPbUVrCjVyZDBuRWxIN2crM2RCVTZFdFp1OVZLNW9JRm5iQTZTMVFUQmVtNlJhR2MKLT4gMGEtZ3JlYXNlIEwhdldQIHU0UCArIFoubmAKUkxvZWdPTEoxSnR6NnBiaDArdXJGUVkzeDZoL0lxNS8yMjkxUUNRZXRPTDI5cWIraUFXYXkxc3krQzhvVlZXZQpQUmVhQXJWWkZpdVljS2JiNXJhcTFnZkdwdmpxTGZ2czRvOHJGWFdYSUEKLS0tIFpKSkRtZCtqYXh3bnJNOWU1UWdzdUNyOWNCM1RqMjBlSGNaMkk4SDhrZGMKVLLna7ZrOzU8bcGjAj8k8iaQJOKTlbLQX36atsjXal3L5BLrgO+NdOVxOZvxaceP7orsdFXY6k3J8ZQxHKV0vIY6ePOxwTWrvQEgCQN6egzPb/NL89MojusmGL1AAYJFGkEJLhF566HjRKHYcsYoztqBb7VernaHVicVZkw" }
