[tools]
rust = "latest"

[env]
GH_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa2VQOWNQVHI3VzRXdkFWY0MyNC9Rc3QvdkQ3KzB1L3FaUEtpTFRiUlNBCk1Vc2RORkw1L2hDcTVQd0VYaVBNQmFiT3VOWmdzUDh5Um1xS0tyQUg3Nm8KLT4gaS1ncmVhc2Ugejhvdy0lIHoKRE5mYVA2S2Y1Tzh0cFNSSUx2d3NGTU1RYlo1aUZHMmZESFY1eUE1MkprOAotLS0gWkx0RTBYNTlkczJ5emR0OWJFM2lLSjF6YXc3RFVXVEJPN0Qwb3VmdkZDSQp/dNHwLb0JSV/a8z9pPmpRLg/8fVUL5ARUSxs+VhJWsdeunWv90QJkF/DOL9X77+4qi6+N7tQ/uEzO1e4VnvOs74+TOqTT38tHnhVPtdYbrTtkzaJUileTiZQajszUkdHS0nSnGy/pVtavlNTa8rMgHZnHePv796x1CgeYsA" }
